#!/bin/sh --
# articlemenu

# Copyright (c) 2017 Denis Kasak
# Distributed under the ISC licence.

# requires calibredb jq rofi xdg-open

ARTICLE_STORE=~/docs/articles

getarticles() {
    find "$ARTICLE_STORE" \( -type f -or -type l \) -and -not -path '*/.*' -printf '%P\0'
}

launchreader() {
    # shellcheck disable=SC2039
    local article
    read -r article
    xdg-open "$ARTICLE_STORE/$article"
}

menu() {
    rofi -dmenu -i -lines 20 -p "articlemenu: "
}

choice=$(getarticles | sort -z | sed -e 's/\x0/\n/g' | menu)

if [ -z "$choice" ]; then
    exit -1
fi

printf "%s" "$choice" | launchreader
