#!/usr/bin/python
# emojimenu - Display an emoji entry menu using rofi
#
# Functionally equivalent to rofi-emoji but uses python instead of jq and sh

# Copyright (c) 2017 Denis Kasak
# Distributed under the ISC licence.

# requires python, rofi, xdotool
#
# Also requires an emoji definition file which can be found here:
# https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

# INSTALL:
#   1. mkdir -p "$XDG_DATA_HOME"
#   2. cp emoji.json $XDG_DATA_HOME/emoji.json

import json
import subprocess
import os


def emoji_menu_item(emoji_def):
    category = emoji_def['category']
    emoji = emoji_def['emoji']
    desc = emoji_def['description']

    return f'|{category}| {emoji} {desc}'


xdg_data_home = os.getenv('XDG_DATA_HOME')
if not xdg_data_home:
    xdg_data_home = os.path.join(os.getenv('HOME'), '.local', 'share')

emoji_file = os.path.join(xdg_data_home, 'emoji.json')

# load emoji definitions
emojis = json.load(open(emoji_file))
emoji_menu_items = [emoji_menu_item(e) for e in emojis
                    if 'description' in e
                    if 'emoji' in e]

# display menu
rofi_cmd = ['rofi', '-dmenu', '-i', '-lines', '20', '-p', 'emoji: ']
selection = subprocess.check_output(rofi_cmd,
                                    input='\n'.join(emoji_menu_items),
                                    encoding="utf-8")

# strip newline
selection = selection.rstrip()
emoji = selection.split(' ')[1]

# type emoji in focused window
subprocess.call(['xdotool', 'type', emoji])
