#!/usr/bin/python3
# emojimenu - Display an emoji entry menu using rofi
#
# Functionally equivalent to rofi-emoji but uses python instead of jq and sh

# Copyright (c) 2017 Denis Kasak
# Distributed under the ISC licence.

# requires python, rofi, xdotool
#
# Also requires an emoji definition file which can be found here:
# https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

# INSTALL:
#   1. mkdir -p "$XDG_DATA_HOME"
#   2. cp emoji.json $XDG_DATA_HOME/emoji.json

import json
import subprocess
import os

# SETTINGS
#
# values:
#   - method: type, paste
#   - register: clipboard, primary
#   - key: any key mnemonic accepted by xdotool

paste_methods = {
    "termite": {"method":   "type"},           # noqa
    "kitty":   {"method":   "paste",           # noqa
                "register": "primary",         # noqa
                "key":      "Shift+Insert"},   # noqa
}

default_method = {"method": "paste",
                  "register": "clipboard",
                  "key": "Control+v"}


def emoji_menu_item(emoji_def):
    category = '{:>10}'.format('|' + emoji_def['category'] + '|')
    emoji = emoji_def['emoji']
    desc = emoji_def['description']

    if emoji_def['tags']:
        tags = (tag for tag in emoji_def['tags'] if tag != desc)
        formatted_tags = '[' + ', '.join(tags) + ']'
    else:
        formatted_tags = ''

    return f'{category} {emoji} {desc} {formatted_tags}'


def focused_window_classes():
    # get the currently focused window class
    window_id = subprocess.check_output(["xdotool", "getwindowfocus"])
    classes = subprocess.check_output(["xprop", "-id", window_id, "WM_CLASS"],
                                      encoding="utf-8")
    classes = [c.strip('"')
               for c in classes.split('=', 1)[1].strip().split(', ')]

    return classes


def determine_method(classes):
    for c in classes:
        method = paste_methods.get(c)
        if method:
            return method

    return default_method


xdg_data_home = os.getenv('XDG_DATA_HOME')
if not xdg_data_home:
    xdg_data_home = os.path.join(os.getenv('HOME'), '.local', 'share')

emoji_file = os.path.join(xdg_data_home, 'emoji.json')

# load emoji definitions
emojis = json.load(open(emoji_file))
emoji_menu_items = [emoji_menu_item(e) for e in emojis
                    if 'description' in e
                    if 'emoji' in e]

# display menu
rofi_cmd = ['rofi', '-sync', '-dmenu', '-i', '-lines', '10', '-p', 'emoji']
selection = subprocess.check_output(rofi_cmd,
                                    input='\n'.join(emoji_menu_items),
                                    encoding="utf-8")


# strip newline
selection = selection.rstrip()
emoji = selection.split('|')[2].strip().split()[0]

paste_method = determine_method(focused_window_classes())

if paste_method['method'] == 'type':
    # type the emoji
    subprocess.call(['xdotool', 'type', emoji])
elif paste_method['method'] == 'paste':
    register = paste_method.get('register', 'clipboard')
    flag = '-b' if register == 'clipboard' else '-p'

    # put the emoji into the clipboard, saving the current clipboard content
    saved_clipboard = subprocess.check_output(['xsel', '-io', flag],
                                              input=emoji,
                                              encoding="utf-8")

    # tell the program to paste
    subprocess.call(['xdotool', 'key', paste_method['key']])

    # restore the clipboard
    subprocess.check_output(["xsel", "-i", flag],
                            input=saved_clipboard,
                            encoding="utf-8")
