#!/bin/sh
# rofi-emoji - create a menu for emoji selection

# Copyright (c) 2017 Damir Jelić.
# Distributed under the ISC licence.

# requires jq rofi xdotool
# A suitable emoji data file can be found at:
# https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

# POSIX sh with local
# shellcheck disable=SC2039

DEFAULT_DATA_HOME="$HOME/.local/share"
emojiFile="${XDG_DATA_HOME:-$DEFAULT_DATA_HOME}/emoji.json"

getEmojiData() {
    jq -r '.[] | select(has("emoji")) | [ "|" + .category + "|", .emoji, .description] | join(" ") | @text'
}

menu() {
    rofi -dmenu -i -location 6 -lines 10 -p "emojimenu: "
}

typeIt() {
    local emoji

    while read -r emoji; do
        if [ "$emoji" ]; then
            xdotool type "$emoji"
        fi
    done
}

getEmojiData < "$emojiFile" | menu | cut -d' ' -f 2 | typeIt
