#!/bin/sh
# rofi-emoji - create a menu for emoji selection

# Copyright (c) 2017 Damir Jelić.
# Distributed under the ISC licence.

# requires jq rofi xdotool
# A suitable emoji data file can be found at:
# https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

# POSIX sh with local
# shellcheck disable=SC2039

emojiFile="$XDG_DATA_HOME/emoji.json"

getEmojiData() {
    jq -r ".[] | [.emoji, .description] | @tsv"
}

menu() {
    rofi -dmenu -i -location 6 -lines 10 -p "emojimenu: "
}

typeIt() {
    local emoji

    while read -r emoji; do
        if [ "$emoji" ]; then
            xdotool type "$emoji"
        fi
    done
}

getEmojiData < "$emojiFile" | menu | cut -f 1 | typeIt
